services:
  api-auth:
    build: .
    container_name: api-auth-hex
    ports:
      - '3001:3001'
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
